/* This file is is generated by a shell script.  DO NOT EDIT! */

/* emulate the original gld for the given plan9_i386
   Copyright 1991, 1992, 1994, 1996, 2000
   Free Software Foundation, Inc.
   Written by Steve Chamberlain steve@cygnus.com

This file is part of GLD, the Gnu Linker.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.  */

#define TARGET_IS_plan9_i386

#include "bfd.h"
#include "sysdep.h"
#include "bfdlink.h"

#include "ld.h"
#include "ldmain.h"
#include "ldmisc.h"

#include "ldexp.h"
#include "ldlang.h"
#include "ldfile.h"
#include "ldemul.h"

static void gldplan9_i386_before_parse PARAMS ((void));
static char *gldplan9_i386_get_script PARAMS ((int *isfile));

static void
gldplan9_i386_before_parse()
{
#ifndef TARGET_			/* I.e., if not generic.  */
  ldfile_set_output_arch ("i386");
#endif /* not TARGET_ */
}

static char *
gldplan9_i386_get_script(isfile)
     int *isfile;
{			     
  *isfile = 0;

  if (link_info.relocateable == true && config.build_constructors == true)
    return
"OUTPUT_FORMAT(\"plan9-i386\")\n\
OUTPUT_ARCH(i386)\n\
SECTIONS\n\
{\n\
  .text :\n\
  {\n\
    CREATE_OBJECT_SYMBOLS\n\
    *(.text)\n\
  }\n\
  .data :\n\
  {\n\
    *(.data)\n\
    CONSTRUCTORS\n\
  }\n\
  .bss :\n\
  {\n\
    ;\n\
    *(.bss)\n\
    *(COMMON)\n\
    ;\n\
    ;\n\
  }\n\
}\n\n"
  ; else if (link_info.relocateable == true) return
"OUTPUT_FORMAT(\"plan9-i386\")\n\
OUTPUT_ARCH(i386)\n\
SECTIONS\n\
{\n\
  .text :\n\
  {\n\
    CREATE_OBJECT_SYMBOLS\n\
    *(.text)\n\
  }\n\
  .data :\n\
  {\n\
    *(.data)\n\
  }\n\
  .bss :\n\
  {\n\
    ;\n\
    *(.bss)\n\
    *(COMMON)\n\
    ;\n\
    ;\n\
  }\n\
}\n\n"
  ; else if (!config.text_read_only) return
"OUTPUT_FORMAT(\"plan9-i386\")\n\
OUTPUT_ARCH(i386)\n\
SEARCH_DIR(/lib); SEARCH_DIR(/usr/lib); SEARCH_DIR(/386/lib/gnu); SEARCH_DIR(/usr/local/lib); SEARCH_DIR(/386/bin/gnu/i386-lucent-plan9/lib);\n\
PROVIDE (__stack = 0);\n\
SECTIONS\n\
{\n\
  . = 0x1020;\n\
  .text :\n\
  {\n\
    CREATE_OBJECT_SYMBOLS\n\
    *(.text)\n\
    _etext = .;\n\
    __etext = .;\n\
  }\n\
  . = .;\n\
  .data :\n\
  {\n\
    *(.data)\n\
    CONSTRUCTORS\n\
    _edata  =  .;\n\
    __edata  =  .;\n\
  }\n\
  .bss :\n\
  {\n\
     __bss_start = .;\n"
"    *(.bss)\n\
    *(COMMON)\n\
    _end = . ;\n\
    __end = . ;\n\
  }\n\
}\n\n"
  ; else if (!config.magic_demand_paged) return
"OUTPUT_FORMAT(\"plan9-i386\")\n\
OUTPUT_ARCH(i386)\n\
SEARCH_DIR(/lib); SEARCH_DIR(/usr/lib); SEARCH_DIR(/386/lib/gnu); SEARCH_DIR(/usr/local/lib); SEARCH_DIR(/386/bin/gnu/i386-lucent-plan9/lib);\n\
PROVIDE (__stack = 0);\n\
SECTIONS\n\
{\n\
  . = 0x1020;\n\
  .text :\n\
  {\n\
    CREATE_OBJECT_SYMBOLS\n\
    *(.text)\n\
    _etext = .;\n\
    __etext = .;\n\
  }\n\
  . = ALIGN(0x1000);\n\
  .data :\n\
  {\n\
    *(.data)\n\
    CONSTRUCTORS\n\
    _edata  =  .;\n\
    __edata  =  .;\n\
  }\n\
  .bss :\n\
  {\n\
     __bss_start = .;\n"
"    *(.bss)\n\
    *(COMMON)\n\
    _end = . ;\n\
    __end = . ;\n\
  }\n\
}\n\n"
  ; else return
"OUTPUT_FORMAT(\"plan9-i386\")\n\
OUTPUT_ARCH(i386)\n\
SEARCH_DIR(/lib); SEARCH_DIR(/usr/lib); SEARCH_DIR(/386/lib/gnu); SEARCH_DIR(/usr/local/lib); SEARCH_DIR(/386/bin/gnu/i386-lucent-plan9/lib);\n\
PROVIDE (__stack = 0);\n\
SECTIONS\n\
{\n\
  . = 0x1020;\n\
  .text :\n\
  {\n\
    CREATE_OBJECT_SYMBOLS\n\
    *(.text)\n\
    _etext = .;\n\
    __etext = .;\n\
  }\n\
  . = ALIGN(0x1000);\n\
  .data :\n\
  {\n\
    *(.data)\n\
    CONSTRUCTORS\n\
    _edata  =  .;\n\
    __edata  =  .;\n\
  }\n\
  .bss :\n\
  {\n\
     __bss_start = .;\n"
"    *(.bss)\n\
    *(COMMON)\n\
    _end = . ;\n\
    __end = . ;\n\
  }\n\
}\n\n"
; }

struct ld_emulation_xfer_struct ld_plan9_i386_emulation = 
{
  gldplan9_i386_before_parse,
  syslib_default,
  hll_default,
  after_parse_default,
  after_open_default,
  after_allocation_default,
  set_output_arch_default,
  ldemul_default_target,
  before_allocation_default,
  gldplan9_i386_get_script,
  "plan9_i386",
  "plan9-i386",
  NULL,	/* finish */
  NULL,	/* create output section statements */
  NULL,	/* open dynamic archive */
  NULL,	/* place orphan */
  NULL,	/* set symbols */
  NULL,	/* parse args */
  NULL,	/* unrecognized file */
  NULL,	/* list options */
  NULL,	/* recognized file */
  NULL 	/* find_potential_libraries */
};
